# **LAB1**

# **BTM1**

In [ ]:
#Cach 1
import numpy as np
my_list = [1, 9, 15, 39]
print('Python list: ', my_list)
my_numpy_array = np.array(my_list)
print('Numpy array: ', my_numpy_array)

Python list:  [1, 9, 15, 39]
Numpy array:  [ 1  9 15 39]


In [ ]:
#Cach 2
import numpy as np
a = np.array([1, 9, 15, 39])
print(a)

[ 1  9 15 39]


# **BT1**

In [ ]:
import numpy as np
random_array = np.random.randint(0, 21, size=(3, 3))

print("Mảng ngẫu nhiên 3x3:")
print(random_array)
all_elements_non_zero = np.all(random_array != 0)

print("\nTất cả các phần tử trong mảng có # 0 không?", all_elements_non_zero)

Mảng ngẫu nhiên 3x3:
[[13  4  6]
 [ 2 18 18]
 [12  7  7]]

Tất cả các phần tử trong mảng có # 0 không? True


# **BT2**

In [ ]:
import numpy as np
new_random_array = np.random.randint(0, 21, size=(3, 3))

print("Mảng ngẫu nhiên 3x3 mới:")
print(new_random_array)

any_element_non_zero = np.any(new_random_array != 0)

print("\nCó tồn tại phần tử nào trong mảng # 0 không?", any_element_non_zero)

Mảng ngẫu nhiên 3x3 mới:
[[ 6 17 12]
 [20 11 12]
 [ 3 18 20]]

Có tồn tại phần tử nào trong mảng # 0 không? True


# **BT3**

### **So sanh mang 1 chieu**

In [ ]:
import numpy as np

# Tạo hai mảng 1 chiều
arr1_1d = np.array([10, 20, 30, 40, 50])
arr2_1d = np.array([15, 20, 25, 40, 55])
scalar_val = 35

print("Mảng 1 chiều 1:", arr1_1d)
print("Mảng 1 chiều 2:", arr2_1d)
print("Giá trị vô hướng:", scalar_val)

print("\n--- numpy.greater (>) ---")
# arr1_1d > arr2_1d (so sánh từng phần tử)
print("arr1_1d > arr2_1d:", np.greater(arr1_1d, arr2_1d))
# arr1_1d > scalar_val
print("arr1_1d > scalar_val:", np.greater(arr1_1d, scalar_val))

print("\n--- numpy.greater_equal (>=) ---")
# arr1_1d >= arr2_1d
print("arr1_1d >= arr2_1d:", np.greater_equal(arr1_1d, arr2_1d))
# arr1_1d >= scalar_val
print("arr1_1d >= scalar_val:", np.greater_equal(arr1_1d, scalar_val))

print("\n--- numpy.less (<) ---")
# arr1_1d < arr2_1d
print("arr1_1d < arr2_1d:", np.less(arr1_1d, arr2_1d))
# arr1_1d < scalar_val
print("arr1_1d < scalar_val:", np.less(arr1_1d, scalar_val))

print("\n--- numpy.less_equal (<=) ---")
# arr1_1d <= arr2_1d
print("arr1_1d <= arr2_1d:", np.less_equal(arr1_1d, arr2_1d))
# arr1_1d <= scalar_val
print("arr1_1d <= scalar_val:", np.less_equal(arr1_1d, scalar_val))


Mảng 1 chiều 1: [10 20 30 40 50]
Mảng 1 chiều 2: [15 20 25 40 55]
Giá trị vô hướng: 35

--- numpy.greater (>) ---
arr1_1d > arr2_1d: [False False  True False False]
arr1_1d > scalar_val: [False False False  True  True]

--- numpy.greater_equal (>=) ---
arr1_1d >= arr2_1d: [False  True  True  True False]
arr1_1d >= scalar_val: [False False False  True  True]

--- numpy.less (<) ---
arr1_1d < arr2_1d: [ True False False False  True]
arr1_1d < scalar_val: [ True  True  True False False]

--- numpy.less_equal (<=) ---
arr1_1d <= arr2_1d: [ True  True False  True  True]
arr1_1d <= scalar_val: [ True  True  True False False]


### **So sanh mang 2 chieu**

In [ ]:
import numpy as np

# Tạo hai mảng 2 chiều
arr1_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2_2d = np.array([[0, 2, 4], [3, 5, 7], [6, 8, 10]])
scalar_val_2d = 5

print("Mảng 2 chiều 1:\n", arr1_2d)
print("Mảng 2 chiều 2:\n", arr2_2d)
print("Giá trị vô hướng:", scalar_val_2d)

print("\n--- numpy.greater (>) ---")
print("arr1_2d > arr2_2d:\n", np.greater(arr1_2d, arr2_2d))
print("arr1_2d > scalar_val_2d:\n", np.greater(arr1_2d, scalar_val_2d))

print("\n--- numpy.greater_equal (>=) ---")
print("arr1_2d >= arr2_2d:\n", np.greater_equal(arr1_2d, arr2_2d))
print("arr1_2d >= scalar_val_2d:\n", np.greater_equal(arr1_2d, scalar_val_2d))

print("\n--- numpy.less (<) ---")
print("arr1_2d < arr2_2d:\n", np.less(arr1_2d, arr2_2d))
print("arr1_2d < scalar_val_2d:\n", np.less(arr1_2d, scalar_val_2d))

print("\n--- numpy.less_equal (<=) ---")
print("arr1_2d <= arr2_2d:\n", np.less_equal(arr1_2d, arr2_2d))
print("arr1_2d <= scalar_val_2d:\n", np.less_equal(arr1_2d, scalar_val_2d))


Mảng 2 chiều 1:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Mảng 2 chiều 2:
 [[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]
Giá trị vô hướng: 5

--- numpy.greater (>) ---
arr1_2d > arr2_2d:
 [[ True False False]
 [ True False False]
 [ True False False]]
arr1_2d > scalar_val_2d:
 [[False False False]
 [False False  True]
 [ True  True  True]]

--- numpy.greater_equal (>=) ---
arr1_2d >= arr2_2d:
 [[ True  True False]
 [ True  True False]
 [ True  True False]]
arr1_2d >= scalar_val_2d:
 [[False False False]
 [False  True  True]
 [ True  True  True]]

--- numpy.less (<) ---
arr1_2d < arr2_2d:
 [[False False  True]
 [False False  True]
 [False False  True]]
arr1_2d < scalar_val_2d:
 [[ True  True  True]
 [ True False False]
 [False False False]]

--- numpy.less_equal (<=) ---
arr1_2d <= arr2_2d:
 [[False  True  True]
 [False  True  True]
 [False  True  True]]
arr1_2d <= scalar_val_2d:
 [[ True  True  True]
 [ True  True False]
 [False False False]]


# **BT4**

In [ ]:
import numpy as np

# Tạo mảng gồm 10 số 1
ones_array = np.ones(10, dtype=int)

# Tạo mảng gồm 10 số 0
zeros_array = np.zeros(10, dtype=int)

# Tạo mảng gồm 10 số 5
fives_array = np.full(10, 5, dtype=int)

# Nối các mảng lại với nhau
final_array = np.concatenate((ones_array, zeros_array, fives_array))

print("Mảng gồm 10 số 1, 10 số 0 và 10 số 5:")
print(final_array)


Mảng gồm 10 số 1, 10 số 0 và 10 số 5:
[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 5 5 5 5 5 5 5 5 5 5]


# **BT5**

In [ ]:
import numpy as np

# Tạo mảng các số nguyên chẵn từ 30 đến 70 (bao gồm cả 70)
even_numbers_array = np.arange(30, 71, 2)

print("Mảng các số nguyên chẵn từ 30 đến 70:")
print(even_numbers_array)


Mảng các số nguyên chẵn từ 30 đến 70:
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


# **BT6**

In [ ]:
import numpy as np

# Tạo ma trận đơn vị 3x3
identity_matrix = np.identity(3)

print("Ma trận đơn vị 3x3:")
print(identity_matrix)


Ma trận đơn vị 3x3:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# **BT7**

In [ ]:
import numpy as np

# Tạo mảng 10 phần tử ngẫu nhiên trong khoảng [15, 55]
random_array_10_elements = np.random.randint(15, 56, size=10)

print("Mảng gốc:", random_array_10_elements)
print("Các giá trị trừ phần tử đầu và cuối:", random_array_10_elements[1:-1])


Mảng gốc: [19 28 19 27 48 51 16 31 54 36]
Các giá trị trừ phần tử đầu và cuối: [28 19 27 48 51 16 31 54]


# **BT8**

In [ ]:
import numpy as np

# Tạo mảng 20 phần tử ngẫu nhiên trong khoảng [0, 20]
random_array_20_elements = np.random.randint(0, 21, size=20)

print("Mảng gốc:", random_array_20_elements)

condition = (random_array_20_elements >= 9) & (random_array_20_elements <= 15)

random_array_20_elements[condition] = -random_array_20_elements[condition]

print("Mảng sau khi đổi dấu các số trong khoảng [9, 15]:", random_array_20_elements)

Mảng gốc: [11  2  7  7 18 12 18  2  9  7 12 15  5  5 10 15 12 19  9  6]
Mảng sau khi đổi dấu các số trong khoảng [9, 15]: [-11   2   7   7  18 -12  18   2  -9   7 -12 -15   5   5 -10 -15 -12  19
  -9   6]


# **BT9**

In [ ]:
import numpy as np

# Tạo ma trận 3x4 với các phần tử ngẫu nhiên trong khoảng [10, 21]
matrix_3x4 = np.random.randint(10, 22, size=(3, 4))

print("Ma trận 3x4:")
print(matrix_3x4)

Ma trận 3x4:
[[17 14 21 11]
 [19 18 21 19]
 [14 16 21 18]]


In [ ]:
import numpy as np

# Tạo ma trận 10x10 toàn số 0
matrix_10x10 = np.zeros((10, 10), dtype=int)

# Đặt các phần tử ở biên thành 1
matrix_10x10[0, :] = 1  # Hàng đầu tiên
matrix_10x10[-1, :] = 1 # Hàng cuối cùng
matrix_10x10[:, 0] = 1  # Cột đầu tiên
matrix_10x10[:, -1] = 1 # Cột cuối cùng

print("Ma trận 10x10 với biên là 1 và bên trong là 0:")
print(matrix_10x10)

# **BT10**

In [ ]:
import numpy as np

# Tạo ma trận 10x10 toàn số 0
matrix_10x10 = np.zeros((10, 10), dtype=int)

matrix_10x10[0, :] = 1
matrix_10x10[-1, :] = 1
matrix_10x10[:, 0] = 1
matrix_10x10[:, -1] = 1

print("Ma trận 10x10 với biên là 1 và bên trong là 0:")
print(matrix_10x10)

Ma trận 10x10 với biên là 1 và bên trong là 0:
[[1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1]]


# **BT11**

In [ ]:
import numpy as np

diagonal_elements = np.array([1, 2, 3, 4, 5])

matrix_diagonal = np.diag(diagonal_elements)

print("Ma trận 5x5 với đường chéo chính là 1, 2, 3, 4, 5:")
print(matrix_diagonal)

Ma trận 5x5 với đường chéo chính là 1, 2, 3, 4, 5:
[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


# **BT12**

In [ ]:
import numpy as np

# Tạo ma trận 3x3x3 với các phần tử ngẫu nhiên trong khoảng [0, 9]
arr_3d = np.arange(27).reshape((3, 3, 3))
print("Mảng 3x3x3 ban đầu:")
print(arr_3d)

# Tính tổng theo mỗi 'dòng' (summing across the last axis - axis=2)
sum_by_row = np.sum(arr_3d, axis=2)
print("\nTổng theo mỗi dòng (sum across axis=2):")
print(sum_by_row)

# Tính tổng theo mỗi 'cột' (summing across the second axis - axis=1)
sum_by_col = np.sum(arr_3d, axis=1)
print("\nTổng theo mỗi cột (sum across axis=1):")
print(sum_by_col)



Mảng 3x3x3 ban đầu:
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]

Tổng theo mỗi dòng (sum across axis=2):
[[ 3 12 21]
 [30 39 48]
 [57 66 75]]

Tổng theo mỗi cột (sum across axis=1):
[[ 9 12 15]
 [36 39 42]
 [63 66 69]]


# **BT13**

In [ ]:
import numpy as np

# Tạo hai vector ngẫu nhiên 10 phần tử
vector1 = np.random.rand(10)
vector2 = np.random.rand(10)

print("Vector 1:", vector1)
print("Vector 2:", vector2)

inner_product = np.dot(vector1, vector2)

print("\nInner product của hai vector là:", inner_product)

Vector 1: [0.52809652 0.45943266 0.58806177 0.82187417 0.07339735 0.18166045
 0.70273789 0.18215994 0.49755167 0.72094724]
Vector 2: [0.23009281 0.29798298 0.17331729 0.10870346 0.13267037 0.61504428
 0.6094002  0.38631868 0.98561982 0.65841596]

Inner product của hai vector là: 2.034843403772954


# **BT14**

In [ ]:
import numpy as np

# Tạo ma trận A kích thước 4x3 với các phần tử ngẫu nhiên
A = np.random.rand(4, 3)
print("Ma trận A (4x3) ban đầu:")
print(A)

y = np.random.rand(3)
print("\nVector y (3 phần tử) ban đầu:")
print(y)

A_plus_y = A + y
print("\nMa trận A sau khi cộng vector y vào mỗi dòng:")
print(A_plus_y)

Ma trận A (4x3) ban đầu:
[[0.97237573 0.17931996 0.44500819]
 [0.72134677 0.08845131 0.71267612]
 [0.70295057 0.95147805 0.85813208]
 [0.3879515  0.11920024 0.4447262 ]]

Vector y (3 phần tử) ban đầu:
[0.92346448 0.16870946 0.75735864]

Ma trận A sau khi cộng vector y vào mỗi dòng:
[[1.89584021 0.34802942 1.20236683]
 [1.64481125 0.25716077 1.47003476]
 [1.62641505 1.12018751 1.61549072]
 [1.31141598 0.2879097  1.20208484]]


# **BT15**

In [ ]:
import pandas as pd

# Tạo hai Series
series1 = pd.Series([2, 4, 6, 8, 10])
series2 = pd.Series([1, 3, 5, 7, 10])

print("Series 1:", series1.values)
print("Series 2:", series2.values)

# Cộng hai Series
sum_series = series1 + series2
print("\nTổng của hai Series:\n", sum_series.values)

# Trừ hai Series
diff_series = series1 - series2
print("\nHiệu của hai Series:\n", diff_series.values)

# Nhân hai Series
prod_series = series1 * series2
print("\nTích của hai Series:\n", prod_series.values)

# Chia hai Series
div_series = series1 / series2
print("\nThương của hai Series:\n", div_series.values)

Series 1: [ 2  4  6  8 10]
Series 2: [ 1  3  5  7 10]

Tổng của hai Series:
 [ 3  7 11 15 20]

Hiệu của hai Series:
 [1 1 1 1 0]

Tích của hai Series:
 [  2  12  30  56 100]

Thương của hai Series:
 [2.         1.33333333 1.2        1.14285714 1.        ]


# **BT16**

In [ ]:
import pandas as pd

# 1. Tạo DataFrame mẫu như trong hình
df = pd.DataFrame({
    'col1': [1, 2, 3, 4, 7, 11],
    'col2': [4, 5, 6, 9, 5, 0],
    'col3': [7, 5, 8, 12, 1, 11]
})

print("DataFrame ban đầu:")
print(df)
print("-" * 30)

s = df.iloc[:, 0]

print("1st column as a Series:")
print(s)

print(f"\nKiểu dữ liệu: {type(s)}")

DataFrame ban đầu:
   col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11
------------------------------
1st column as a Series:
0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64

Kiểu dữ liệu: <class 'pandas.core.series.Series'>


# **BT17**

In [ ]:
import pandas as pd
import numpy as np

# Tạo một DataFrame 4x3 với các giá trị ngẫu nhiên
df_random = pd.DataFrame(np.random.randint(0, 100, size=(4, 3)),
                         columns=['Col_A', 'Col_B', 'Col_C'])

print("DataFrame ngẫu nhiên ban đầu:")
print(df_random)

# Sắp xếp DataFrame theo 'Col_A' theo thứ tự tăng dần (mặc định)
sorted_df_asc = df_random.sort_values(by='Col_A')

print("\nDataFrame sau khi sắp xếp theo 'Col_A' (tăng dần):")
print(sorted_df_asc)

# Sắp xếp DataFrame theo 'Col_B' theo thứ tự giảm dần
sorted_df_desc = df_random.sort_values(by='Col_B', ascending=False)

print("\nDataFrame sau khi sắp xếp theo 'Col_B' (giảm dần):")
print(sorted_df_desc)

DataFrame ngẫu nhiên ban đầu:
   Col_A  Col_B  Col_C
0     26     45      1
1     97      9     49
2     20     49     33
3     99     17     70

DataFrame sau khi sắp xếp theo 'Col_A' (tăng dần):
   Col_A  Col_B  Col_C
2     20     49     33
0     26     45      1
1     97      9     49
3     99     17     70

DataFrame sau khi sắp xếp theo 'Col_B' (giảm dần):
   Col_A  Col_B  Col_C
2     20     49     33
0     26     45      1
3     99     17     70
1     97      9     49


# **BT18**

In [ ]:
import pandas as pd

# 1. Tạo Series ban đầu với index là A, B, C, D, E
data = [1, 2, 3, 4, 5]
index = ['A', 'B', 'C', 'D', 'E']
s = pd.Series(data, index=index)

print("Original Data Series:")
print(s)
print("-" * 30)

new_order = ['B', 'A', 'C', 'D', 'E']
s_new = s.reindex(index=new_order)

print("Data Series after changing the order of index:")
print(s_new)

Original Data Series:
A    1
B    2
C    3
D    4
E    5
dtype: int64
------------------------------
Data Series after changing the order of index:
B    2
A    1
C    3
D    4
E    5
dtype: int64


# **BT19**

In [ ]:
import pandas as pd

# 1. Tạo hai Series sr1 và sr2
sr1 = pd.Series([1, 2, 3, 4, 5])
sr2 = pd.Series([2, 4, 6, 8, 10])

print("sr1:")
print(sr1)
print("\nsr2:")
print(sr2)
print("-" * 30)

# 2. Tìm các phần tử trong sr1 không có trong sr2
result = sr1[~sr1.isin(sr2)]

print("Items of sr1 not present in sr2:")
print(result)

sr1:
0    1
1    2
2    3
3    4
4    5
dtype: int64

sr2:
0     2
1     4
2     6
3     8
4    10
dtype: int64
------------------------------
Items of sr1 not present in sr2:
0    1
2    3
4    5
dtype: int64


# **BT20**

In [ ]:
import pandas as pd
import numpy as np

# 1. Tạo 2 Series x và y ngẫu nhiên có 20 phần tử
np.random.seed(42)
x = pd.Series(np.random.randint(1, 21, 20))
y = pd.Series(np.random.randint(1, 21, 20))

print("Series x:")
print(x.values)
print("\nSeries y:")
print(y.values)
print("-" * 30)

# 2. Tìm Hiệu của 2 tập hợp (Phép Hội - Union)
union_result = np.union1d(x, y)
print("Kết quả phép Hội (Union - x hợp y):")
print(union_result)

# 3. Tìm Giao của 2 tập hợp (Phép Giao - Intersection)
intersect_result = np.intersect1d(x, y)
print("\nKết quả phép Giao (Intersection - x giao y):")
print(intersect_result)

Series x:
[ 7 20 15 11  8  7 19 11 11  4  8  3  2 12  6  2  1 12 12 17]

Series y:
[10 16 15 15 19 12 20  3  5 19  7  9  7 18  4 14 18  9  2 20]
------------------------------
Kết quả phép Hội (Union - x hợp y):
[ 1  2  3  4  5  6  7  8  9 10 11 12 14 15 16 17 18 19 20]

Kết quả phép Giao (Intersection - x giao y):
[ 2  3  4  7 12 15 19 20]


# **BT21**

In [1]:
import pandas as pd

# Tạo hai Series mẫu
x = pd.Series([1, 2, 3, 4, 5], name='Series_X')
y = pd.Series([6, 7, 8, 9, 10], name='Series_Y')

print("Series X:")
print(x)
print("\nSeries Y:")
print(y)

print("\n--- Nối Series theo chiều dọc (Vertical Concatenation) ---")
# pd.concat với axis=0 (mặc định) sẽ nối theo chiều dọc
vertical_concat = pd.concat([x, y], axis=0)
print("Kết quả nối dọc (Vertical Concatenation):")
print(vertical_concat)

print("\n--- Nối Series theo chiều ngang (Horizontal Concatenation) ---")
# pd.concat với axis=1 sẽ nối theo chiều ngang, tạo ra một DataFrame
horizontal_concat = pd.concat([x, y], axis=1)
print("Kết quả nối ngang (Horizontal Concatenation):")
print(horizontal_concat)

Series X:
0    1
1    2
2    3
3    4
4    5
Name: Series_X, dtype: int64

Series Y:
0     6
1     7
2     8
3     9
4    10
Name: Series_Y, dtype: int64

--- Nối Series theo chiều dọc (Vertical Concatenation) ---
Kết quả nối dọc (Vertical Concatenation):
0     1
1     2
2     3
3     4
4     5
0     6
1     7
2     8
3     9
4    10
dtype: int64

--- Nối Series theo chiều ngang (Horizontal Concatenation) ---
Kết quả nối ngang (Horizontal Concatenation):
   Series_X  Series_Y
0         1         6
1         2         7
2         3         8
3         4         9
4         5        10


# **BT22-30**

In [14]:
import pandas as pd
import numpy as np

# --- BÀI 22: Tạo và hiển thị DataFrame ---
exam_data = {
    'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
    'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
    'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
    'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data, index=labels)
print("Bài 22 - DataFrame gốc:")
print(df)
print("-" * 30)

# --- BÀI 23: Hiển thị 3 dòng đầu tiên ---
print("Bài 23 - 3 dòng đầu tiên:")
print(df.head(3))
print("-" * 30)

# --- BÀI 24: Chọn cột 'name' và 'score' ---
print("Bài 24 - Cột name và score:")
print(df[['name', 'score']])
print("-" * 30)

# --- BÀI 25: Những dòng có attempts > 2 ---
print("Bài 25 - Những dòng có attempts > 2:")
print(df[df['attempts'] > 2])
print("-" * 30)

# --- BÀI 26: Số dòng và số cột của DataFrame ---
rows = len(df.axes[0])
cols = len(df.axes[1])
print(f"Bài 26 - Số dòng: {rows}, Số cột: {cols}")
print("-" * 30)

# --- BÀI 27: Những dòng có score là NaN ---
print("Bài 27 - Những dòng có score bị thiếu (NaN):")
print(df[df['score'].isnull()])
print("-" * 30)

# --- BÀI 28: Những dòng có score trong khoảng (15, 20) ---
print("Bài 28 - Score trong khoảng [15, 20]:")
print(df[df['score'].between(15, 20)])
print("-" * 30)

# --- BÀI 29: Những dòng có attempts > 2 và score trong khoảng (15, 20) ---
print("Bài 29 - Kết hợp điều kiện (attempts > 2 và score 15-20):")
print(df[(df['attempts'] > 2) & (df['score'].between(15, 20))])
print("-" * 30)

# --- BÀI 30: Thay đổi giá trị dòng 'd', cột 'score' thành 19 ---
print("Bài 30 - Thay đổi giá trị tại dòng 'd':")
df.loc['d', 'score'] = 19
print(df.loc[['d']])

Bài 22 - DataFrame gốc:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes
------------------------------
Bài 23 - 3 dòng đầu tiên:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
------------------------------
Bài 24 - Cột name và score:
        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0
------------------------------
Bài 25 - Những dòng có attempts > 2:
  