# **BT1**

In [1]:
import tensorflow as tf
t1 = tf.zeros([2, 3])
print(t1)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


# **BT2**

In [2]:
X = tf.constant([[1, 2, 3], [4, 5, 6]])
t2 = tf.zeros_like(X)
print(t2)

tf.Tensor(
[[0 0 0]
 [0 0 0]], shape=(2, 3), dtype=int32)


# **BT3**

In [3]:
t3 = tf.fill([3, 2], 5)
print(t3)

tf.Tensor(
[[5 5]
 [5 5]
 [5 5]], shape=(3, 2), dtype=int32)


# **BT4**

In [4]:
import numpy as np
options = [6, 8, 10]
t4 = tf.constant(np.random.choice(options, 50))
print(t4)

tf.Tensor(
[ 8 10 10  6 10  6  6 10  6  8  8 10  6  8 10  6 10 10  6  6  6  6  8 10
  8 10 10  8 10  6  8  6  6  6  6  8  6  8  8 10 10 10  6  6  8  6  8 10
  6 10], shape=(50,), dtype=int64)


# **BT5**

In [5]:
t5 = tf.range(start=10, limit=101, delta=2)
print(t5)

tf.Tensor(
[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100], shape=(46,), dtype=int32)


# **BT6**

In [6]:
t6 = tf.random.normal([3, 2], mean=0, stddev=2)
print(t6)

tf.Tensor(
[[ 3.0568507   1.744525  ]
 [ 1.0465069   3.1629293 ]
 [-0.52307194  0.10265619]], shape=(3, 2), dtype=float32)


# **BT7**

In [7]:
t7 = tf.random.uniform([3, 2], minval=0, maxval=2)
print(t7)

tf.Tensor(
[[0.19868588 0.4399228 ]
 [0.887141   1.1642563 ]
 [1.1384728  1.3543367 ]], shape=(3, 2), dtype=float32)


# **BT8**

In [8]:
X8 = tf.constant([[1, 2], [3, 4], [5, 6]])
t8 = tf.random.shuffle(X8)
print(t8)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


# **BT9**

In [9]:
t9_raw = tf.random.uniform([10, 10, 3])
t9 = tf.image.random_crop(t9_raw, size=[5, 5, 3])
print("Shape sau khi crop:", t9.shape)

Shape sau khi crop: (5, 5, 3)


# **BT10**

In [10]:
x10 = tf.random.uniform([5], minval=1, maxval=10)
y10 = tf.random.uniform([5], minval=1, maxval=10)
# Trả về x+y nếu x < y, ngược lại x-y
t10 = tf.where(x10 < y10, x10 + y10, x10 - y10)
print("x:", x10.numpy())
print("y:", y10.numpy())
print("Kết quả:", t10.numpy())

x: [6.958314  1.3572348 7.326256  9.761166  2.3435142]
y: [1.9776448 4.0093966 4.3890204 8.202746  3.7557306]
Kết quả: [4.980669  5.3666315 2.9372354 1.5584192 6.099245 ]


# **BT11**

In [12]:
x11 = tf.random.uniform([3, 2], minval=5, maxval=10)
y11 = tf.random.uniform([2, 3], minval=15, maxval=20)

# Lấy giá trị đường chéo của x
diag_x = tf.linalg.diag_part(x11)

# Thực hiện x + y (y đảo hàng thành cột)
result11 = x11 + tf.transpose(y11)

print("Đường chéo x:", diag_x.numpy())
print("Kết quả x + y_transpose:\n", result11.numpy())

Đường chéo x: [9.122443 8.094555]
Kết quả x + y_transpose:
 [[25.729233 23.43526 ]
 [23.872656 23.991043]
 [21.063469 24.595337]]


# **BT12**

In [13]:
import tensorflow as tf

@tf.function # Chuyển hàm vào trong Graph
def compute_tensors(x, y):
    add = tf.add(x, y)
    sub = tf.subtract(x, y)
    mul = tf.multiply(x, y)
    div = tf.divide(x, y)
    return add, sub, mul, div

# Tạo 2 tensor ngẫu nhiên kích thước (3, 2, 2)
x = tf.random.uniform([3, 2, 2])
y = tf.random.uniform([3, 2, 2])

add, sub, mul, div = compute_tensors(x, y)
print("Bài 12 - Kết quả cộng (add):\n", add.numpy())

Bài 12 - Kết quả cộng (add):
 [[[1.4837763  0.45235813]
  [1.0115012  1.0671175 ]]

 [[0.5238644  1.0966722 ]
  [1.622254   0.5281472 ]]

 [[0.48223603 1.4758493 ]
  [1.6523044  0.89123285]]]


# **BT13-14**

In [14]:
class BasicMathModel(tf.Module):
    @tf.function
    def add(self, x, y):
        return x + y

    @tf.function
    def subtract(self, x, y):
        return x - y

    @tf.function
    def multiply(self, x, y):
        return x * y

model = BasicMathModel()
x = tf.constant([10.0, 20.0])
y = tf.constant([2.0, 5.0])

print("Bài 13 - Tổng:", model.add(x, y).numpy())
print("Bài 14 - Hiệu:", model.subtract(x, y).numpy())
print("Bài 14 - Tích:", model.multiply(x, y).numpy())

Bài 13 - Tổng: [12. 25.]
Bài 14 - Hiệu: [ 8. 15.]
Bài 14 - Tích: [ 20. 100.]


# **BT15**

In [15]:
@tf.function
def tinh_chu_vi(a, b):
    return tf.multiply(tf.add(a, b), 2.0)

a = tf.constant(5.0)
b = tf.constant(3.0)
print(f"Bài 15 - Chu vi HCN (5, 3): {tinh_chu_vi(a, b).numpy()}")

Bài 15 - Chu vi HCN (5, 3): 16.0


# **BT16**

In [16]:
@tf.function
def tinh_dien_tich_tp(a, b, c):
    s_xung_quanh = (a + b) * c * 2
    s_toan_phan = (a * b) * 2 + s_xung_quanh
    return s_toan_phan

a, b, c = tf.constant(2.0), tf.constant(3.0), tf.constant(4.0)
print(f"Bài 16 - Diện tích toàn phần: {tinh_dien_tich_tp(a, b, c).numpy()}")

Bài 16 - Diện tích toàn phần: 52.0


# **BT17**

In [17]:
@tf.function
def check_parallel(AD_val, BC_val, AB_val, CD_val, is_parallel_input):
    # Kiểm tra điều kiện vế phải: AD = BC và AB = CD
    cond = tf.logical_and(tf.equal(AD_val, BC_val), tf.equal(AB_val, CD_val))
    # Trả về True nếu cả hai vế tương đương nhau
    return tf.equal(is_parallel_input, cond)

# Ví dụ: AD=5, BC=5, AB=3, CD=3 và giả định AD // BC là True
print("Bài 17 - Điều kiện đúng hay không:", check_parallel(5, 5, 3, 3, True).numpy())

Bài 17 - Điều kiện đúng hay không: True


# **BT18**

In [18]:
@tf.function
def check_equal_bases(AB_val, CD_val, AD_val, BC_val, is_parallel):
    # Điều kiện vế phải: AD = BC và AD // BC (is_parallel là True)
    cond = tf.logical_and(tf.equal(AD_val, BC_val), is_parallel)
    # So sánh với vế trái AB = CD
    return tf.equal(tf.equal(AB_val, CD_val), cond)

# Ví dụ
print("Bài 18 - Kiểm tra tính đúng đắn:", check_equal_bases(4, 4, 6, 6, True).numpy())

Bài 18 - Kiểm tra tính đúng đắn: True


# **BT19**

In [19]:
import tensorflow as tf

@tf.function
def chung_minh_duong_trung_binh(AM, MB, AN, NC, MN, BC, is_parallel_MN_BC):
    """
    Xây dựng model chứng minh NA = NC dựa trên các điều kiện đầu vào.
    is_parallel_MN_BC: Tensor kiểu Boolean (True nếu MN // BC)
    """

    # 1. Kiểm tra điều kiện M là trung điểm AB (AM = MB)
    is_M_midpoint = tf.equal(AM, MB)

    # 2. Kiểm tra điều kiện MN là đường trung bình
    condition_to_prove = tf.logical_and(tf.equal(MN, MB), is_parallel_MN_BC)

    # 3. Kết luận NA = NC nếu thỏa mãn điều kiện trên
    is_proven = tf.logical_and(condition_to_prove, tf.equal(AN, NC))

    return is_proven

# --- Ví dụ ---
# Giả sử: AM=3, MB=3 (M là trung điểm), AN=4, NC=4, MN=3, BC=6 và MN // BC
AM = tf.constant(3.0)
MB = tf.constant(3.0)
AN = tf.constant(4.0)
NC = tf.constant(4.0)
MN = tf.constant(3.0)
BC = tf.constant(6.0)
is_parallel = tf.constant(True)

result = chung_minh_duong_trung_binh(AM, MB, AN, NC, MN, BC, is_parallel)

print("Kết quả chứng minh NA = NC:")
if result.numpy():
    print("=> Chứng minh THÀNH CÔNG: Điều kiện thỏa mãn để N là trung điểm AC.")
else:
    print("=> Chứng minh THẤT BẠI: Các điều kiện đầu vào không khớp.")

Kết quả chứng minh NA = NC:
=> Chứng minh THÀNH CÔNG: Điều kiện thỏa mãn để N là trung điểm AC.
